[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
object = "0.32.1"
im = "15.1.0"
floem = { git = "https://github.com/lapce/floem.git" }
rfd = "0.12"
symbolic-demangle = "12.4.1"
symbolic-common = "12.4.1"
